spring:
  application:
    name: user
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      username: admin
      password: P@ssw0rd
